export const DEFAULT_ACTION = 'update/DEFAULT_ACTION'
export const FETCH_ACTION = 'update/FETCH_ACTION'
export const FETCH_SUCCESS_ACTION = 'update/FETCH_SUCCESS_ACTION'
export const FETCH_FAILED_ACTION = 'update/FETCH_FAILED_ACTION'